### ISSUE TITLE
Latest release breaks with SvelteKit: `<Icon>` is not a valid SSR component

### ISSUE THREAD

**Issue by iolyd** [lucide-icons/lucide#1536]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [X] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.270.0

### Browser

- [X] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [X] macOS
- [ ] Other/not relevant

### Description

Using icons from the latest release is unfit for SvelteKit's SSR. Reverting to version `0.269.0` works.

### Steps to reproduce

1. Import any icon as a named export (`import { User } from 'lucide-svelte'`)
2. `pnpm dev`
3. Observe logs

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by erskingardner** [comment]
+1 – I'm also having this same issue.

**Comment by shirotech** [comment]
dist/esm folder is missing in the new build

**Comment by delight** [comment]
bug is still in 0.271.0 ... 
0.269.0 works

**Comment by bfovez** [comment]
The bug is still present in 0.274.0!
No comment from the lucide team on this major issue. Does they even care?

**Comment by bfovez** [comment]
The bug is still present in 0.274.0

**Comment by Gerschtli** [comment]
This bug was likely caused by https://github.com/lucide-icons/lucide/pull/1499

**Comment by ericfennis** [comment]
Working on it!

**Comment by ericfennis** [comment]
Sorry for the late response.

Released beta version on `lucide-svelte@0.275.0-beta.0`

Please have check if it now works.

```
```

**Comment by delight** [comment]
lucide-svelte@0.275.0-beta.0 works for me

**Comment by Gerschtli** [comment]
For me too, thank you!

**Comment by axeltaylor** [comment]
> Sorry for the late response.
> 
> Released beta version on `lucide-svelte@0.275.0-beta.0`
> 
> Please have check if it now works.
> 
> ```
> npm install lucide-svelte@0.275.0-beta.0
> ```
> 
> Thanks to @JanTrichter for the fix in #1499

Using astro and the integration with svelte works too, thank you!

**Comment by delight** [comment]
@ericfennis When are we going to see a release of lucide-svelte that fixes this problem ?

**Comment by ericfennis** [comment]
@delight Sorry we had some problems with duplicated alias/icon names. I just merged the fix #1555. All failed builds need to be released again. I will rerelease everything today. Including the fixes for lucide-svelte. I will post update when I'm done.

**Comment by JayeshVP24** [comment]
Hey, its still broken in stable release. Any update on this?

**Comment by delight** [comment]
> Hey @ericfennis , its still broken in latest stable release. Any update on this?

Are you sure about this? What version are you using? I ain't got no issues with the latest versions no more.

**Comment by Wizzel1** [comment]
I am still getting this error with version 0.279.0

**Comment by JayeshVP24** [comment]
> > Hey @ericfennis , its still broken in latest stable release. Any update on this?
> 
> Are you sure about this? What version are you using? I ain't got no issues with the latest versions no more.

yes I'm sure, version v0.279.0. For now I downgraded to v0.69.0

**Comment by JayeshVP24** [comment]
> > Hey @ericfennis , its still broken in latest stable release. Any update on this?
> 
> Are you sure about this? What version are you using? I ain't got no issues with the latest versions no more.

umm nvm, Ig my package manager didn't update the cached package and even though it was 0.279.0 in package.json, it was using old ones. 
I use PNPM, so I simply ran `pnpm up lucide-svelte --latest` which resolved my issue. 
Don't know if this is pnpm specific issue or any package manager who uses cache mechanism.
Thanks.

**Comment by JayeshVP24** [comment]
> I am still getting this error with version 0.279.0

try downgrading it to 0.269.0 then updating it using your package manager...
ig you are using pnpm as well, run `pnpm up lucide-svelte --latest` after downgrading.
This will update all cache's

**Comment by Wizzel1** [comment]
> > I am still getting this error with version 0.279.0
> 
> try downgrading it to 0.269.0 then updating it using your package manager... ig you are using pnpm as well, run `pnpm up lucide-svelte --latest` after downgrading. This will update all cache's

Yeah seems to be working now, thanks!

**Comment by OliverGilan** [comment]
I'm getting the same issue with `0.376.0`

**Comment by OliverGilan** [comment]
Downgrading to `0.372.0` fixes it. Something must have broken since then

**Comment by ericfennis** [comment]
@OliverGilan Hmm wierd, I will check!

**Comment by aristelecom** [comment]
I am using https://www.shadcn-svelte.com/docs and experiencing the same problem, I managed to solve it by downgrading to 0.372.0

`Error when evaluating SSR module /node_modules/.pnpm/lucide-svelte@0.376.0_svelte@4.2.10/node_modules/lucide-svelte/dist/Icon.svelte: failed to import "@lucide/shared"
|- Error: Cannot find module '@lucide/shared'`

pnpm install  lucide-svelte@0.372.0

- lucide-svelte 0.376.0
+ lucide-svelte 0.372.0


This worked

**Comment by travisdmathis** [comment]
this issue still exists in 0.383.0, downgrading to 0.372.0 fixed the issue

**Comment by ericfennis** [comment]
@travisdmathis, did you also try removing node_modules and trying again? It works on my side with no problems.

**Comment by travisdmathis** [comment]
i'll give that a shot eric, issue popped up when building a capacitorjs/svelte app.

**Comment by Peyman-Borhani** [comment]
@ericfennis 
I have same/similar issue, using on shadcn-svelte, pnpm, JS and no TS.  I tried few versions, including 0.372 and 0.419.0  -  I did above suggestions, yet no difference, I get multiple errors, like this:

Error: <Package2> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules. Otherwise you may need to fix a <Package2>.

**Comment by ericfennis** [comment]
Will check

**Comment by erroid** [comment]
I got error 500 when I try to use an icon @ SvelteKit with Svelte 5 + TS + vite
