### ISSUE TITLE
"React is not defined" error when working with 'lucide-solid' in SolidJS

### ISSUE THREAD

**Issue by SamstyleGhost** [lucide-icons/lucide#1602]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [X] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.286.0

### Browser

- [X] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [X] Other/not relevant

### Operating system

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] Other/not relevant

### Description

When adding an icon into a SolidJS project using the documentation on [lucide-solid documentation website](https://lucide.dev/guide/packages/lucide-solid), there is an error in the console: 
![image](https://github.com/lucide-icons/lucide/assets/97402158/5adfeb0f-25f5-48cd-af61-69567233c493)
It also breaks the entire application.

### Steps to reproduce

1. Start a Solid project
2. Install the 'lucide-solid' library using npm
3. Import any icon and render it in a component
4. The console would show 'React not defined' error

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by ericfennis** [comment]
@SamstyleGhost Hmm I checked it, but it works fine on my machine.
Did you setup your `tsconfig` correctly?
These lines should be present otherwise it will fallback on the default JSX createElement which uses `React`.
```json
    "jsx": "preserve",
    "jsxImportSource": "solid-js",
```

Otherwise it would be nice if you can provide a reproduction repository or a [Stackblitz](https://stackblitz.com/).

**Comment by outbackStack** [comment]
I have the same issue using solidjs.  I deleted the `node_modules` folder and install everything again and it seems to work fine now. Not sure what's going there.

**Comment by outbackStack** [comment]
The new solid 1.8 came out a few days ago and it's causing a few issues with SVG.
https://github.com/solidjs/solid/issues/1911#issue-1935918218

**Comment by outbackStack** [comment]
Recent release of `solid 1.8.0` is causing a few issues with SVG but not sure if this is the cause.
https://github.com/solidjs/solid/issues/1911

**Comment by ericfennis** [comment]
> I have the same issue using solidjs. I deleted the `node_modules` folder and install everything again and it seems to work fine now. Not sure what's going there.

I can't reproduce this one. I mark this one as solved with the solution from @outbackStack.

**Comment by raviqqe** [comment]
For anyone encoutering this error with Astro.js, see https://docs.astro.build/en/guides/typescript/#errors-typing-multiple-jsx-frameworks-at-the-same-time.

**Comment by mrchantey** [comment]
I'm still getting this in an Astro project, tried removing `node_modules` and `tsconfig.json` is set up with jsx specified:
```
{
  "compilerOptions": {
    "jsx": "preserve",
    "jsxImportSource": "solid-js",
  }
}
```

**Comment by mrchantey** [comment]
I was getting this too but my problem wasn't lucide, it was due to an overly specific `include` in the `astro.config` solid plugin.

**Comment by dameekoh** [comment]
I've had this problem now. Fixed it by putting macaronVitePlugin before solid in vite.config.ts. Apparently, the order mattered xD
