### ISSUE TITLE
expo-router iOS build is crashing after installing and using Lucide react-native icons.

### ISSUE THREAD

**Issue by ritmillio** [lucide-icons/lucide#1783]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [X] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.306.0

### Browser

- [ ] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [ ] macOS
- [X] Other/not relevant

### Description

Install lucide-react-native to an expo-router project. When I run the app locally on Expo Go there is no issue whatsoever but as soon as I build the app for production iOS App Store , after testing the app on Test Flight It crashes immediatelly.

### Steps to reproduce

1. Install lucide-react-native to a plain expo-router project
2. Use one lucide icon in one of the component.
3. Build and submit app via EAS
4. Testflight build will crash immediatelly

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by ritmillio** [comment]
is there any update on this ? I would love to use lucide-react with expo-router

**Comment by He1nr1chK** [comment]
I am experiencing the same issue when trying to use the dynamic icons as specified here: [](https://lucide.dev/guide/packages/lucide-react-native#icon-component-example)

**Comment by gpaiva985** [comment]
> is there any update on this ? I would love to use lucide-react with expo-router

Hey @ritmillio, did you find a workaround for this?

**Comment by ritmillio** [comment]
@gpaiva985 This is fixed. You can use lucide-react-native with expo-router now :) Also make sure that react-native-svg latest version is installed.

Here's a simple example how you might do that in TypeScript:

    
    import React from 'react';
    import { icons, LucideProps } from 'lucide-react-native';
    import { ColorValue } from 'react-native';
    
    interface IconProps {
      name: keyof typeof icons;
      color?: ColorValue;
      size?: LucideProps['size'];
    }
    
    const Icon: React.FC<IconProps> = ({ name, color, size }) => {
      const LucideIcon: React.FC<LucideProps & { color?: ColorValue }> =
        icons[name];
    
      return <LucideIcon color={color} size={size} />;
    };
    
    export default Icon;

**Comment by diogotl** [comment]
It still doesnt work for me.

I tried to use @ritmillio solution and even in a very basic use like  `<Icon name="Eye" size={24} color="#F09F27" /> ` It throws the following error in LogCat when I try to render a view with a Lucide icon on it.

Invariant Violation: requireNativeComponent: "RNSVGPath" was not found in the UIManager.

**Comment by ritmillio** [comment]
@diogotl Hey, This error tells me that there is an issue with react-native-svg in your project. It's either not installed or not the correct version installed. When I built my app I used react-native-svg: 14.1.0 and lucide-react-native: 0.359.0.

**Comment by diogotl** [comment]
@ritmillio Thank you!! I was using an older version although expo doctor said it was the latest version!

By the way, this error was also occurring with Android builds. Hopefully, it can be helpful to someone.

**Comment by gpaiva985** [comment]
> @gpaiva985 This is fixed. You can use lucide-react-native with expo-router now :) Also make sure that react-native-svg latest version is installed.
> 
> Here's a simple example how you might do that in TypeScript:
> 
> ```
> import React from 'react';
> import { icons, LucideProps } from 'lucide-react-native';
> import { ColorValue } from 'react-native';
> 
> interface IconProps {
>   name: keyof typeof icons;
>   color?: ColorValue;
>   size?: LucideProps['size'];
> }
> 
> const Icon: React.FC<IconProps> = ({ name, color, size }) => {
>   const LucideIcon: React.FC<LucideProps & { color?: ColorValue }> =
>     icons[name];
> 
>   return <LucideIcon color={color} size={size} />;
> };
> 
> export default Icon;
> ```

Got it, thanks! Everything is working great!

**Comment by wetterkrank** [comment]
Hi! Just to let you know -- came across this issue, updated the packages, still getting the error (`Invariant Violation: requireNativeComponent: "RNSVGPath" was not found in the UIManager`).
```
"react-native-svg": "14.1.0",
"lucide-react-native": "0.363.0",
```

**Comment by DaltonHarvey** [comment]
> er not installed or not the correct version. When I built my app I used react-native-svg: 14.1.0 and lucide-

Same

**Comment by redshoga** [comment]
FYI

I had the same issue. 
Installing the following package solved the problem for me.

```
"react-native-svg": "^15.2.0"
```

**Comment by mfbevan** [comment]
> FYI
> 
> I had the same issue. Installing the following package solved the problem for me.
> 
> ```
> "react-native-svg": "^15.2.0"
> ```
> 
> The environment in which it worked is described below.
> 
> ```
> "react": "18.2.0",
> "react-native": "0.74.5",
> "expo": "~51.0.28",
> "lucide-react-native": "^0.454.0",
> ```

Can confirm that adding `react-native-svg` worked for me. Using:

    "lucide-react-native": "^0.474.0",
    "react-native-svg": "^15.11.1",
    react: 18.3.1
    "expo": "~52.0.27",
