### ISSUE TITLE
lucide-react@0.471.1 doesn't work on Next.js

### ISSUE THREAD

**Issue by krankos** [lucide-icons/lucide#2739]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [X] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.471.1

### Can you reproduce this in the latest version?

- [X] Yes
- [ ] No

### Browser

- [ ] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [X] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [ ] macOS
- [ ] ChromeOS
- [ ] iOS
- [ ] Android
- [X] Other/not relevant

### Description

version 0.470.0 works fine. when using version 0.471.1 in Next.js 15 with React 19, I get this error

```
Type error: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("lucide-react")' call instead.
```

### Steps to reproduce

1. import any icon

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by ericfennis** [comment]
Should be fixed in lucide-react@0.472.0

**Comment by stevejcox** [comment]
@ericfennis - still seeing the same issue. Not seeing a type change [between 0.471.0 and 0.472.0](https://github.com/lucide-icons/lucide/compare/0.471.1...0.472.0)?

**Comment by lluiscab** [comment]
This issue is definitely not fixed as of `lucide-react@0.473.0`:

```
error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("lucide-react")' call instead.
  To convert this file to an ECMAScript module, add the field `"type": "module"` to '<redacted>/package.json'.

import { ChevronDown } from 'lucide-react';
````

Why was `lucide-react` converted to ESM on a patch (`0.471.1`)?
