### ISSUE TITLE
lucide-react-native adding ~13k lines of repeated license text to production output bundle expo-router/web

### ISSUE THREAD

**Issue by gorbypark** [lucide-icons/lucide#3744]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [x] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] lucide-astro
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.548.0

### Can you reproduce this in the latest version?

- [x] Yes
- [ ] No

### Browser

- [ ] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [x] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [ ] macOS
- [ ] ChromeOS
- [ ] iOS
- [ ] Android
- [x] Other/not relevant

### Description

When using lucide-react-native in an expo-router based expo project on the web (metro bundling for web), if you do `npx expo export --platform web` and then inspect the `entry_xxxx.js` bundle, there is about 13,000 lines of text that is just the repeated lucide license text.  I haven't counted it up, but I'm assuming it's one license per lucide icon?

I'm guessing when serving the bundle the servers compression will take care of mostly compressing it away, but it does seem a bit excessive!

```
const u=(0,((e=t)&&e.__esModule?e:{default:e}).default)("ZoomIn",[["circle",{cx:"11",cy:"11",r:"8",key:"4ej97u"}],["line",{x1:"21",x2:"16.65",y1:"21",y2:"16.65",key:"13gj7c"}],["line",{x1:"11",x2:"11",y1:"8",y2:"14",key:"1vmskp"}],["line",{x1:"8",x2:"14",y1:"11",y2:"11",key:"durymu"}]])},5122,[3462]);
__d(function(g,r,i,a,m,_e,d){"use strict";Object.defineProperty(_e,'__esModule',{value:!0}),Object.defineProperty(_e,"default",{enumerable:!0,get:function(){return u}});var e,t=r(d[0]);
/**
   * @license lucide-react-native v0.548.0 - ISC
   *
   * This source code is licensed under the ISC license.
   * See the LICENSE file in the root directory of this source tree.
   */
```
this is just repeated over and over after each icon.  Probably another issue, but this makes me think that "tree shaking" is not working, because every single icon is being included in the bundle, whether used or not.

### Steps to reproduce

1. add react native lucide to project
2. use a single icon
3. run `npx expo expo -p web`
4. inspect entry_xxx.js create from step 3

### Checklist

- [x] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by mariepowerscrews** [comment]
### Option 1: The "I fixed it, here is how" (Best for quick help)

This is a great, standard open-source contribution style. It validates the issue and provides the direct fix.

> I ran into this as well. It looks like the issue is that the Metro minifier (Terser) defaults to preserving comments marked as "legal" or `@license`. Since Lucide includes that header in every single icon file, they stack up massively in the final bundle.
>
> You can strip them out by explicitly telling Metro to drop comments in your `metro.config.js`:
>
> ```javascript
> `const { getDefaultConfig } = require('expo/metro-config');`
> ```

> const config = getDefaultConfig(\_\_dirname);

> config.transformer.minifierConfig = {
> // This tells the minifier (terser) to remove all comments, including licenses
> output: {
> comments: false,
> },
> };

> module.exports = config;
>
> ```
> 
> Regarding your note on tree-shaking: seeing the licenses repeated doesn't *always* mean tree-shaking failed (it might just be preserving the headers of the used modules), but if you want to be 100% sure you aren't bundling unused icons, using deep imports (e.g. `import X from 'lucide-react-native/icons/X'`) is usually the safest bet.
> ```

-----

### Option 2: Short & Sweet (If you just want to drop the code)

> This happens because the minifier preserves `@license` comments by default. You can force it to strip them in `metro.config.js` to clean up the bundle:
>
> ```javascript
> config.transformer.minifierConfig = {
>   output: {
>     comments: false,
>   },
> };
> ```
>
> That cleared up the 13k+ lines for me.

-----

### Option 3: The "Deep Dive" (Addresses the tree-shaking concern more thoroughly)

Use this if you want to sound like you really dug into the architecture.

> I did some digging on this. The massive text block is definitely because Metro/Terser is configured to keep "legal comments" (anything with `@license` or `ISC`) in the production build. Since Lucide splits icons into separate files, each one carries its own license header, and they all get concatenated.
>
> **The Fix:**
> You can silence this in `metro.config.js` by setting `output.comments` to `false` in the `minifierConfig`.
>
> **Re: Tree Shaking**
> You mentioned specifically that *"every single icon is being included in the bundle, whether used or not."*
>
> If you are using standard named imports (`import { Icon } from...`), Metro *should* shake them, but sometimes the license headers remain even if the code functions are stripped. If you suspect the actual code is still there, try switching to deep imports to force exclusion:
>
> `import Icon from 'lucide-react-native/icons/IconName';`

**Comment by vugarbbakhishov-hub** [comment]
This is still present in the current published `lucide-react-native@1.46.0` tarball. I measured the per-icon ESM modules directly:

- `dist/esm/icons/` contains 1,839 JavaScript modules
- all 1,839 contain the same `@license` banner
- the banners account for 11,034 lines and 327,342 bytes
- that is 21.9% of the 1,498,009 source bytes in those per-icon modules

Those numbers describe the published sources; whether all banners survive in a consumer bundle depends on Metro/Terser legal-comment handling. Their presence alone also does not establish that icon code failed to tree-shake.

There is a licensing tradeoff before removing them from generated files: the ISC text requires the notice to be included in copies or substantial portions. If the per-file banners are deliberate for that reason, documenting a Metro minifier setting may be safer than removing them at generation time. The current package data at least confirms the repeated text itself has not gone away.
