### ISSUE TITLE
Stable Font Codepoints

### ISSUE THREAD

**Issue by lilithium-hydride** [lucide-icons/lucide#514]
## Prerequisites

* Version: Releases v0.17.0 - v1.17.1
* Running from: `lucide.ttf`
* Operating system: Artix Linux x86_64

## Step to reproduce

1. Use an older release's codepoints in something.
2. Make note of the icons that are rendered from those codepoints.
3. Update the font file to the latest release without adjusting the codepoints.
4. Observe that the rendered icons are different.

### Actual behavior

1. Use an older release's codepoints in something.
2. Make note of the icons that are rendered from those codepoints.
3. Update the font file to the latest release without adjusting the codepoints.
3. Observe that the rendered icons do not change between releases.

## Any message or error

N/A

## Resources

![Left: new, Right: old](https://user-images.githubusercontent.com/78992082/155236408-900e6bdb-7d01-49c0-82f5-1f26257995d7.png)

## Context

It's currently necessary to pay close attention to the font version when using it outside of a web environment. I understand that this would make it practically impossible to keep icon locations neatly organized, but this shouldn't hurt the web development side of things at all, and would make it far less painful for font users to keep up with releases.

**Comment by ericfennis** [comment]
@lilithium-hydride Tnx for reporting not sure why this happens, we need to check the build.

**Comment by ericfennis** [comment]
Is fixed in #1413 !

**Comment by agorgl** [comment]
Commenting here to let the authors know that this issue is NOT fixed, and has occurred so far 2 times in a period of some months I've been using lucide font. More details on specific versions that this can be reproduced in issue https://github.com/lucide-icons/lucide/issues/3619

**Comment by ericfennis** [comment]
Duplicate of #3619
