### ISSUE TITLE
Concerns related to SSR

### ISSUE THREAD

**Issue by R-Bower** [lucide-icons/lucide#979]
lucide-angular is accessing the `document` object directly in the [createElement](https://github.com/lucide-icons/lucide/blob/main/packages/lucide-angular/src/helpers/create-element.ts) function.  This isn't recommended for SSR as `document` isn't defined in browser-less environments.

Recommendations:
1. Use the Renderer2 abstraction instead, although this would be limited to Components and Directives.
```
constructor(
  element: ElementRef,
  renderer: Renderer2, 
  [tag, attrs, children = []]: IconData
) {
   const element = this.renderer.createElement(tag, "http://www.w3.org/2000/svg")
}
```

2. Use the `DOCUMENT` injection token.
```
import {Inject} from '@angular/core';
import { DOCUMENT } from '@angular/common';
@Component({...}) // could be a service too!
export class MyComponent {
  constructor (@Inject(DOCUMENT) private document: Document) {}
}
```

Between the two options, 1. is probably the safer call.  As per the [docs](https://angular.io/api/common/DOCUMENT):
> Document might not be available in the Application Context when Application and Rendering Contexts are not the same (e.g. when running the application in a Web Worker).

**Comment by ericfennis** [comment]
@R-Bower Thanks for letting us know.
We currently working on the new version of the `lucide-angular` package. See #949 .
We released a beta version on `lucide-angular@0.125.0-beta.0` I'm curious if that version will fix this issue.

**Comment by R-Bower** [comment]
Based on the in-progress work on that PR, the issue with the `document` global is still present.

https://github.com/lucide-icons/lucide/blob/248c5e352af2b1d6d8df2919cc390bc8dcc5bf57/packages/lucide-angular/src/helpers/create-element.ts

**Comment by ericfennis** [comment]
@R-Bower thanks for checking.
@karsa-mistmere Maybe we should fix this in the next version as well.

**Comment by karsa-mistmere** [comment]
Nice catch, @R-Bower, I've updated the PR accordingly. I'm totally in favour of deprecating the `createElement`.
